openapi: '3.0.3'

info:
  description: CSE186 Assignment 8
  version: 0.1.0
  title: CSE186 Assignment 8

servers:
  - url: http://localhost:3010

paths:
  /login:
    post:
      description: Login
      requestBody:
        description: Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        200:
          description: Emails Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'
  /v0/mail:
    get:
      description: Returns all EMail, (optional) a particular mailbox.
      
      parameters:
        # /v0/mail?mailbox={mailbox}
        - in: query
          name: mailbox
          description: Name of the mailbox
          required: false
          schema:
            type: string

        # /v0/mail?from={from}
        - in: query
          name: from
          description: Search from (partial or full name or email)
          required: false
          schema:
            type: string
                  
      responses:
        200:
          description: Email Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MailboxMail'
        404:
          description: Not Found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      description: Saves the receieved email in the request (and returns it).

      requestBody:
        description: Email to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewMail'

      responses:
        200:
          description: Email Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Email'
                  - type: object
                    properties:
                      content:
                        type: string
        400:
          description: Unexpected Properties
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v0/mail/{id}:
    get:
      description: Returns an email with a specific ID.
      
      parameters:
        # /v0/mail/{id}
        - in: path
          name: id
          description: UUID of an Email.
          required: true
          schema:
            type: string
      
      responses:
        200:
          description: Email Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Email'
                  - type: object
                    properties:
                      content:
                        type: string

        404:
          description: Not Found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    put:
      description: Moves email identified by {id} into {mailbox}.
      
      parameters:
        # /v0/mail/{id}
        - in: path
          name: id
          description: UUID of an Email.
          required: true
          schema:
            type: string
        
        # /v0/mail?mailbox={mailbox}
        - in: query
          name: mailbox
          description: Name of the mailbox
          required: true
          schema:
            type: string
      
      responses:
        204:
          description: PUT Success
        404:
          description: Not Found
        409:
          description: Cannot move to "Sent"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    MailboxMail:
      type: object
      properties:
        name:
          type: string
        mail:
          type: array
          items:
            $ref: '#/components/schemas/Email'

    # for GET
    Email:
      type: object
      properties:
        id:
          type: string
        from:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
              format: email
        to:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
              format: email
        subject:
          type: string
        sent:
          type: string
        received:
          type: string
      required:
        - id
        - from
        - to
        - subject
        - sent
        - received

    # for POST
    "NewMail": {
      "type": "object",
      "properties": {
        "to": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "email": {
              "type": "string",
              "format": "email"
            }
          },
          "required": [
            "name",
            "email",
          ],
          "additionalProperties": false
        },
        "subject": {
          "type": "string"
        },
        "content": {
          "type": "string"
        }
      },
      "required": [
        "subject",
        "content",
        "to",
      ],
      "additionalProperties": false
    }
