DELETE FROM user;
INSERT INTO user(email, pname, hash) VALUES ('srheam0@myspace.com', 'Shandra Rheam', 'hash')
INSERT INTO user(email, pname, hash) VALUES ('zjefferys1@vimeo.com', 'Zerk Jefferys', 'hash')
INSERT INTO user(email, pname, hash) VALUES ('bgrain2@usgs.gov', 'Burtie Grain', 'hash')
INSERT INTO user(email, pname, hash) VALUES ('mblasius3@youtube.com', 'Mireielle Blasius', 'hash')
INSERT INTO user(email, pname, hash) VALUES ('sashfold4@soup.io', 'Sheffy Ashfold', 'hash')
INSERT INTO user(email, pname, hash) VALUES ('wbrisardg@lycos.com', 'Wayland Brisard', 'hash')
INSERT INTO user(email, pname, hash) VALUES ('mcullumm@zimbio.com', 'Merrielle Cullum', 'hash')
INSERT INTO user(email, pname, hash) VALUES ('geastopp@uol.com.br', 'Giuditta Eastop', 'hash')
INSERT INTO user(email, pname, hash) VALUES ('tdielhennr@eepurl.com', 'Timi Dielhenn', 'hash')
INSERT INTO user(email, pname, hash) VALUES ('averev@shareasale.com', 'Andy Vere', 'hash')
INSERT INTO user(email, pname, hash) VALUES ('cshortoy@geocities.jp', 'Cybill Shorto', 'hash')
INSERT INTO user(email, pname, hash) VALUES ('apennycord13@nih.gov', 'Antoine Pennycord', 'hash')